//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34014
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This code was auto-generated by Microsoft.Silverlight.Phone.ServiceReference, version 3.7.0.0
// 
namespace WinPhoneClientProxy.ProductManagerService {
    using System.Runtime.Serialization;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="BookBlockPLVM", Namespace="http://schemas.datacontract.org/2004/07/CommonPortable.Models.ProductModels")]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(WinPhoneClientProxy.ProductManagerService.InCategoryPLVM))]
    public partial class BookBlockPLVM : object, System.ComponentModel.INotifyPropertyChanged {
        
        private WinPhoneClientProxy.ProductManagerService.BookBlockType BookBlockTypeField;
        
        private WinPhoneClientProxy.ProductManagerService.Paging PagingField;
        
        private System.Collections.ObjectModel.ObservableCollection<WinPhoneClientProxy.ProductManagerService.InBookBlockPVM> ProductsField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public WinPhoneClientProxy.ProductManagerService.BookBlockType BookBlockType {
            get {
                return this.BookBlockTypeField;
            }
            set {
                if ((this.BookBlockTypeField.Equals(value) != true)) {
                    this.BookBlockTypeField = value;
                    this.RaisePropertyChanged("BookBlockType");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public WinPhoneClientProxy.ProductManagerService.Paging Paging {
            get {
                return this.PagingField;
            }
            set {
                if ((object.ReferenceEquals(this.PagingField, value) != true)) {
                    this.PagingField = value;
                    this.RaisePropertyChanged("Paging");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Collections.ObjectModel.ObservableCollection<WinPhoneClientProxy.ProductManagerService.InBookBlockPVM> Products {
            get {
                return this.ProductsField;
            }
            set {
                if ((object.ReferenceEquals(this.ProductsField, value) != true)) {
                    this.ProductsField = value;
                    this.RaisePropertyChanged("Products");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Paging", Namespace="http://schemas.datacontract.org/2004/07/CommonPortable.Models")]
    public partial class Paging : object, System.ComponentModel.INotifyPropertyChanged {
        
        private int ActualPageNumberField;
        
        private int NumberOfPagesField;
        
        private int NumberOfProductsField;
        
        private int ProductsPerPageField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ActualPageNumber {
            get {
                return this.ActualPageNumberField;
            }
            set {
                if ((this.ActualPageNumberField.Equals(value) != true)) {
                    this.ActualPageNumberField = value;
                    this.RaisePropertyChanged("ActualPageNumber");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int NumberOfPages {
            get {
                return this.NumberOfPagesField;
            }
            set {
                if ((this.NumberOfPagesField.Equals(value) != true)) {
                    this.NumberOfPagesField = value;
                    this.RaisePropertyChanged("NumberOfPages");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int NumberOfProducts {
            get {
                return this.NumberOfProductsField;
            }
            set {
                if ((this.NumberOfProductsField.Equals(value) != true)) {
                    this.NumberOfProductsField = value;
                    this.RaisePropertyChanged("NumberOfProducts");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ProductsPerPage {
            get {
                return this.ProductsPerPageField;
            }
            set {
                if ((this.ProductsPerPageField.Equals(value) != true)) {
                    this.ProductsPerPageField = value;
                    this.RaisePropertyChanged("ProductsPerPage");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="InCategoryPLVM", Namespace="http://schemas.datacontract.org/2004/07/CommonPortable.Models.ProductModels")]
    public partial class InCategoryPLVM : WinPhoneClientProxy.ProductManagerService.BookBlockPLVM {
        
        private WinPhoneClientProxy.ProductManagerService.InCategoryPLVM.CategoryVM CategoryField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public WinPhoneClientProxy.ProductManagerService.InCategoryPLVM.CategoryVM Category {
            get {
                return this.CategoryField;
            }
            set {
                if ((object.ReferenceEquals(this.CategoryField, value) != true)) {
                    this.CategoryField = value;
                    this.RaisePropertyChanged("Category");
                }
            }
        }
        
        [System.Diagnostics.DebuggerStepThroughAttribute()]
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
        [System.Runtime.Serialization.DataContractAttribute(Name="InCategoryPLVM.CategoryVM", Namespace="http://schemas.datacontract.org/2004/07/CommonPortable.Models.ProductModels")]
        public partial class CategoryVM : object, System.ComponentModel.INotifyPropertyChanged {
            
            private string DisplayNameField;
            
            private string FriendlyUrlField;
            
            private string FullPathField;
            
            [System.Runtime.Serialization.DataMemberAttribute()]
            public string DisplayName {
                get {
                    return this.DisplayNameField;
                }
                set {
                    if ((object.ReferenceEquals(this.DisplayNameField, value) != true)) {
                        this.DisplayNameField = value;
                        this.RaisePropertyChanged("DisplayName");
                    }
                }
            }
            
            [System.Runtime.Serialization.DataMemberAttribute()]
            public string FriendlyUrl {
                get {
                    return this.FriendlyUrlField;
                }
                set {
                    if ((object.ReferenceEquals(this.FriendlyUrlField, value) != true)) {
                        this.FriendlyUrlField = value;
                        this.RaisePropertyChanged("FriendlyUrl");
                    }
                }
            }
            
            [System.Runtime.Serialization.DataMemberAttribute()]
            public string FullPath {
                get {
                    return this.FullPathField;
                }
                set {
                    if ((object.ReferenceEquals(this.FullPathField, value) != true)) {
                        this.FullPathField = value;
                        this.RaisePropertyChanged("FullPath");
                    }
                }
            }
            
            public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
            
            protected void RaisePropertyChanged(string propertyName) {
                System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
                if ((propertyChanged != null)) {
                    propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
                }
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="BookBlockType", Namespace="http://schemas.datacontract.org/2004/07/CommonPortable.Enums")]
    public enum BookBlockType : int {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Product = 0,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        ProductGroup = 1,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        ProductInCart = 2,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        ProductInOrder = 3,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        ProductInExchangeCart = 4,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        ProductForExchange = 5,
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="InBookBlockPVM", Namespace="http://schemas.datacontract.org/2004/07/CommonPortable.Models.ProductModels")]
    public partial class InBookBlockPVM : object, System.ComponentModel.INotifyPropertyChanged {
        
        private WinPhoneClientProxy.ProductManagerService.InBookBlockPVM.ProductVM ProductField;
        
        private WinPhoneClientProxy.ProductManagerService.InBookBlockPVM.ProductGroupVM ProductGroupField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public WinPhoneClientProxy.ProductManagerService.InBookBlockPVM.ProductVM Product {
            get {
                return this.ProductField;
            }
            set {
                if ((object.ReferenceEquals(this.ProductField, value) != true)) {
                    this.ProductField = value;
                    this.RaisePropertyChanged("Product");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public WinPhoneClientProxy.ProductManagerService.InBookBlockPVM.ProductGroupVM ProductGroup {
            get {
                return this.ProductGroupField;
            }
            set {
                if ((object.ReferenceEquals(this.ProductGroupField, value) != true)) {
                    this.ProductGroupField = value;
                    this.RaisePropertyChanged("ProductGroup");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
        
        [System.Diagnostics.DebuggerStepThroughAttribute()]
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
        [System.Runtime.Serialization.DataContractAttribute(Name="InBookBlockPVM.ProductVM", Namespace="http://schemas.datacontract.org/2004/07/CommonPortable.Models.ProductModels")]
        public partial class ProductVM : object, System.ComponentModel.INotifyPropertyChanged {
            
            private string DescriptionField;
            
            private int HowManyField;
            
            private int IDField;
            
            private string ImageUrlField;
            
            private bool IsDownloadableField;
            
            private string PriceStringField;
            
            private int ProductInOrderIdField;
            
            private string UserFriendlyUrlField;
            
            private string UserNameField;
            
            [System.Runtime.Serialization.DataMemberAttribute()]
            public string Description {
                get {
                    return this.DescriptionField;
                }
                set {
                    if ((object.ReferenceEquals(this.DescriptionField, value) != true)) {
                        this.DescriptionField = value;
                        this.RaisePropertyChanged("Description");
                    }
                }
            }
            
            [System.Runtime.Serialization.DataMemberAttribute()]
            public int HowMany {
                get {
                    return this.HowManyField;
                }
                set {
                    if ((this.HowManyField.Equals(value) != true)) {
                        this.HowManyField = value;
                        this.RaisePropertyChanged("HowMany");
                    }
                }
            }
            
            [System.Runtime.Serialization.DataMemberAttribute()]
            public int ID {
                get {
                    return this.IDField;
                }
                set {
                    if ((this.IDField.Equals(value) != true)) {
                        this.IDField = value;
                        this.RaisePropertyChanged("ID");
                    }
                }
            }
            
            [System.Runtime.Serialization.DataMemberAttribute()]
            public string ImageUrl {
                get {
                    return this.ImageUrlField;
                }
                set {
                    if ((object.ReferenceEquals(this.ImageUrlField, value) != true)) {
                        this.ImageUrlField = value;
                        this.RaisePropertyChanged("ImageUrl");
                    }
                }
            }
            
            [System.Runtime.Serialization.DataMemberAttribute()]
            public bool IsDownloadable {
                get {
                    return this.IsDownloadableField;
                }
                set {
                    if ((this.IsDownloadableField.Equals(value) != true)) {
                        this.IsDownloadableField = value;
                        this.RaisePropertyChanged("IsDownloadable");
                    }
                }
            }
            
            [System.Runtime.Serialization.DataMemberAttribute()]
            public string PriceString {
                get {
                    return this.PriceStringField;
                }
                set {
                    if ((object.ReferenceEquals(this.PriceStringField, value) != true)) {
                        this.PriceStringField = value;
                        this.RaisePropertyChanged("PriceString");
                    }
                }
            }
            
            [System.Runtime.Serialization.DataMemberAttribute()]
            public int ProductInOrderId {
                get {
                    return this.ProductInOrderIdField;
                }
                set {
                    if ((this.ProductInOrderIdField.Equals(value) != true)) {
                        this.ProductInOrderIdField = value;
                        this.RaisePropertyChanged("ProductInOrderId");
                    }
                }
            }
            
            [System.Runtime.Serialization.DataMemberAttribute()]
            public string UserFriendlyUrl {
                get {
                    return this.UserFriendlyUrlField;
                }
                set {
                    if ((object.ReferenceEquals(this.UserFriendlyUrlField, value) != true)) {
                        this.UserFriendlyUrlField = value;
                        this.RaisePropertyChanged("UserFriendlyUrl");
                    }
                }
            }
            
            [System.Runtime.Serialization.DataMemberAttribute()]
            public string UserName {
                get {
                    return this.UserNameField;
                }
                set {
                    if ((object.ReferenceEquals(this.UserNameField, value) != true)) {
                        this.UserNameField = value;
                        this.RaisePropertyChanged("UserName");
                    }
                }
            }
            
            public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
            
            protected void RaisePropertyChanged(string propertyName) {
                System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
                if ((propertyChanged != null)) {
                    propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
                }
            }
        }
        
        [System.Diagnostics.DebuggerStepThroughAttribute()]
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
        [System.Runtime.Serialization.DataContractAttribute(Name="InBookBlockPVM.ProductGroupVM", Namespace="http://schemas.datacontract.org/2004/07/CommonPortable.Models.ProductModels")]
        public partial class ProductGroupVM : object, System.ComponentModel.INotifyPropertyChanged {
            
            private string AuthorNamesField;
            
            private string CategoryFriendlyUrlField;
            
            private string CategoryFullPathField;
            
            private string DescriptionField;
            
            private string FriendlyUrlField;
            
            private string ImageUrlField;
            
            private bool IsCheckedByAdminField;
            
            private string PublisherNameField;
            
            private int RatingPointsField;
            
            private string SubTitleField;
            
            private int SumOfRatingsField;
            
            private string TitleField;
            
            [System.Runtime.Serialization.DataMemberAttribute()]
            public string AuthorNames {
                get {
                    return this.AuthorNamesField;
                }
                set {
                    if ((object.ReferenceEquals(this.AuthorNamesField, value) != true)) {
                        this.AuthorNamesField = value;
                        this.RaisePropertyChanged("AuthorNames");
                    }
                }
            }
            
            [System.Runtime.Serialization.DataMemberAttribute()]
            public string CategoryFriendlyUrl {
                get {
                    return this.CategoryFriendlyUrlField;
                }
                set {
                    if ((object.ReferenceEquals(this.CategoryFriendlyUrlField, value) != true)) {
                        this.CategoryFriendlyUrlField = value;
                        this.RaisePropertyChanged("CategoryFriendlyUrl");
                    }
                }
            }
            
            [System.Runtime.Serialization.DataMemberAttribute()]
            public string CategoryFullPath {
                get {
                    return this.CategoryFullPathField;
                }
                set {
                    if ((object.ReferenceEquals(this.CategoryFullPathField, value) != true)) {
                        this.CategoryFullPathField = value;
                        this.RaisePropertyChanged("CategoryFullPath");
                    }
                }
            }
            
            [System.Runtime.Serialization.DataMemberAttribute()]
            public string Description {
                get {
                    return this.DescriptionField;
                }
                set {
                    if ((object.ReferenceEquals(this.DescriptionField, value) != true)) {
                        this.DescriptionField = value;
                        this.RaisePropertyChanged("Description");
                    }
                }
            }
            
            [System.Runtime.Serialization.DataMemberAttribute()]
            public string FriendlyUrl {
                get {
                    return this.FriendlyUrlField;
                }
                set {
                    if ((object.ReferenceEquals(this.FriendlyUrlField, value) != true)) {
                        this.FriendlyUrlField = value;
                        this.RaisePropertyChanged("FriendlyUrl");
                    }
                }
            }
            
            [System.Runtime.Serialization.DataMemberAttribute()]
            public string ImageUrl {
                get {
                    return this.ImageUrlField;
                }
                set {
                    if ((object.ReferenceEquals(this.ImageUrlField, value) != true)) {
                        this.ImageUrlField = value;
                        this.RaisePropertyChanged("ImageUrl");
                    }
                }
            }
            
            [System.Runtime.Serialization.DataMemberAttribute()]
            public bool IsCheckedByAdmin {
                get {
                    return this.IsCheckedByAdminField;
                }
                set {
                    if ((this.IsCheckedByAdminField.Equals(value) != true)) {
                        this.IsCheckedByAdminField = value;
                        this.RaisePropertyChanged("IsCheckedByAdmin");
                    }
                }
            }
            
            [System.Runtime.Serialization.DataMemberAttribute()]
            public string PublisherName {
                get {
                    return this.PublisherNameField;
                }
                set {
                    if ((object.ReferenceEquals(this.PublisherNameField, value) != true)) {
                        this.PublisherNameField = value;
                        this.RaisePropertyChanged("PublisherName");
                    }
                }
            }
            
            [System.Runtime.Serialization.DataMemberAttribute()]
            public int RatingPoints {
                get {
                    return this.RatingPointsField;
                }
                set {
                    if ((this.RatingPointsField.Equals(value) != true)) {
                        this.RatingPointsField = value;
                        this.RaisePropertyChanged("RatingPoints");
                    }
                }
            }
            
            [System.Runtime.Serialization.DataMemberAttribute()]
            public string SubTitle {
                get {
                    return this.SubTitleField;
                }
                set {
                    if ((object.ReferenceEquals(this.SubTitleField, value) != true)) {
                        this.SubTitleField = value;
                        this.RaisePropertyChanged("SubTitle");
                    }
                }
            }
            
            [System.Runtime.Serialization.DataMemberAttribute()]
            public int SumOfRatings {
                get {
                    return this.SumOfRatingsField;
                }
                set {
                    if ((this.SumOfRatingsField.Equals(value) != true)) {
                        this.SumOfRatingsField = value;
                        this.RaisePropertyChanged("SumOfRatings");
                    }
                }
            }
            
            [System.Runtime.Serialization.DataMemberAttribute()]
            public string Title {
                get {
                    return this.TitleField;
                }
                set {
                    if ((object.ReferenceEquals(this.TitleField, value) != true)) {
                        this.TitleField = value;
                        this.RaisePropertyChanged("Title");
                    }
                }
            }
            
            public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
            
            protected void RaisePropertyChanged(string propertyName) {
                System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
                if ((propertyChanged != null)) {
                    propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
                }
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ProductManagerService.IProductManager")]
    public interface IProductManager {
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="http://tempuri.org/IProductManager/GetProductsInCategory", ReplyAction="http://tempuri.org/IProductManager/GetProductsInCategoryResponse")]
        System.IAsyncResult BeginGetProductsInCategory(string categoryFriendlyUrl, int pageNumber, int productsPerPage, System.AsyncCallback callback, object asyncState);
        
        WinPhoneClientProxy.ProductManagerService.InCategoryPLVM EndGetProductsInCategory(System.IAsyncResult result);
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="http://tempuri.org/IProductManager/GetMainHighlighteds", ReplyAction="http://tempuri.org/IProductManager/GetMainHighlightedsResponse")]
        System.IAsyncResult BeginGetMainHighlighteds(int pageNumber, int productsPerPage, System.AsyncCallback callback, object asyncState);
        
        WinPhoneClientProxy.ProductManagerService.BookBlockPLVM EndGetMainHighlighteds(System.IAsyncResult result);
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="http://tempuri.org/IProductManager/GetNewests", ReplyAction="http://tempuri.org/IProductManager/GetNewestsResponse")]
        System.IAsyncResult BeginGetNewests(int pageNumber, int productsPerPage, int numOfProducts, System.AsyncCallback callback, object asyncState);
        
        WinPhoneClientProxy.ProductManagerService.BookBlockPLVM EndGetNewests(System.IAsyncResult result);
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="http://tempuri.org/IProductManager/GetUsersProductsByFriendlyUrl", ReplyAction="http://tempuri.org/IProductManager/GetUsersProductsByFriendlyUrlResponse")]
        System.IAsyncResult BeginGetUsersProductsByFriendlyUrl(string friendlyUrl, int pageNumber, int productsPerPage, bool forExchange, System.AsyncCallback callback, object asyncState);
        
        WinPhoneClientProxy.ProductManagerService.BookBlockPLVM EndGetUsersProductsByFriendlyUrl(out string userName, System.IAsyncResult result);
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="http://tempuri.org/IProductManager/GetUsersProducts", ReplyAction="http://tempuri.org/IProductManager/GetUsersProductsResponse")]
        System.IAsyncResult BeginGetUsersProducts(int userID, int pageNumber, int productsPerPage, bool forExchange, System.AsyncCallback callback, object asyncState);
        
        WinPhoneClientProxy.ProductManagerService.BookBlockPLVM EndGetUsersProducts(System.IAsyncResult result);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IProductManagerChannel : WinPhoneClientProxy.ProductManagerService.IProductManager, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class GetProductsInCategoryCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        public GetProductsInCategoryCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        public WinPhoneClientProxy.ProductManagerService.InCategoryPLVM Result {
            get {
                base.RaiseExceptionIfNecessary();
                return ((WinPhoneClientProxy.ProductManagerService.InCategoryPLVM)(this.results[0]));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class GetMainHighlightedsCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        public GetMainHighlightedsCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        public WinPhoneClientProxy.ProductManagerService.BookBlockPLVM Result {
            get {
                base.RaiseExceptionIfNecessary();
                return ((WinPhoneClientProxy.ProductManagerService.BookBlockPLVM)(this.results[0]));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class GetNewestsCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        public GetNewestsCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        public WinPhoneClientProxy.ProductManagerService.BookBlockPLVM Result {
            get {
                base.RaiseExceptionIfNecessary();
                return ((WinPhoneClientProxy.ProductManagerService.BookBlockPLVM)(this.results[0]));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class GetUsersProductsByFriendlyUrlCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        public GetUsersProductsByFriendlyUrlCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        public string userName {
            get {
                base.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
        
        public WinPhoneClientProxy.ProductManagerService.BookBlockPLVM Result {
            get {
                base.RaiseExceptionIfNecessary();
                return ((WinPhoneClientProxy.ProductManagerService.BookBlockPLVM)(this.results[1]));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class GetUsersProductsCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        public GetUsersProductsCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        public WinPhoneClientProxy.ProductManagerService.BookBlockPLVM Result {
            get {
                base.RaiseExceptionIfNecessary();
                return ((WinPhoneClientProxy.ProductManagerService.BookBlockPLVM)(this.results[0]));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ProductManagerClient : System.ServiceModel.ClientBase<WinPhoneClientProxy.ProductManagerService.IProductManager>, WinPhoneClientProxy.ProductManagerService.IProductManager {
        
        private BeginOperationDelegate onBeginGetProductsInCategoryDelegate;
        
        private EndOperationDelegate onEndGetProductsInCategoryDelegate;
        
        private System.Threading.SendOrPostCallback onGetProductsInCategoryCompletedDelegate;
        
        private BeginOperationDelegate onBeginGetMainHighlightedsDelegate;
        
        private EndOperationDelegate onEndGetMainHighlightedsDelegate;
        
        private System.Threading.SendOrPostCallback onGetMainHighlightedsCompletedDelegate;
        
        private BeginOperationDelegate onBeginGetNewestsDelegate;
        
        private EndOperationDelegate onEndGetNewestsDelegate;
        
        private System.Threading.SendOrPostCallback onGetNewestsCompletedDelegate;
        
        private BeginOperationDelegate onBeginGetUsersProductsByFriendlyUrlDelegate;
        
        private EndOperationDelegate onEndGetUsersProductsByFriendlyUrlDelegate;
        
        private System.Threading.SendOrPostCallback onGetUsersProductsByFriendlyUrlCompletedDelegate;
        
        private BeginOperationDelegate onBeginGetUsersProductsDelegate;
        
        private EndOperationDelegate onEndGetUsersProductsDelegate;
        
        private System.Threading.SendOrPostCallback onGetUsersProductsCompletedDelegate;
        
        private BeginOperationDelegate onBeginOpenDelegate;
        
        private EndOperationDelegate onEndOpenDelegate;
        
        private System.Threading.SendOrPostCallback onOpenCompletedDelegate;
        
        private BeginOperationDelegate onBeginCloseDelegate;
        
        private EndOperationDelegate onEndCloseDelegate;
        
        private System.Threading.SendOrPostCallback onCloseCompletedDelegate;
        
        public ProductManagerClient() {
        }
        
        public ProductManagerClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ProductManagerClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ProductManagerClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ProductManagerClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public System.Net.CookieContainer CookieContainer {
            get {
                System.ServiceModel.Channels.IHttpCookieContainerManager httpCookieContainerManager = this.InnerChannel.GetProperty<System.ServiceModel.Channels.IHttpCookieContainerManager>();
                if ((httpCookieContainerManager != null)) {
                    return httpCookieContainerManager.CookieContainer;
                }
                else {
                    return null;
                }
            }
            set {
                System.ServiceModel.Channels.IHttpCookieContainerManager httpCookieContainerManager = this.InnerChannel.GetProperty<System.ServiceModel.Channels.IHttpCookieContainerManager>();
                if ((httpCookieContainerManager != null)) {
                    httpCookieContainerManager.CookieContainer = value;
                }
                else {
                    throw new System.InvalidOperationException("Unable to set the CookieContainer. Please make sure the binding contains an HttpC" +
                            "ookieContainerBindingElement.");
                }
            }
        }
        
        public event System.EventHandler<GetProductsInCategoryCompletedEventArgs> GetProductsInCategoryCompleted;
        
        public event System.EventHandler<GetMainHighlightedsCompletedEventArgs> GetMainHighlightedsCompleted;
        
        public event System.EventHandler<GetNewestsCompletedEventArgs> GetNewestsCompleted;
        
        public event System.EventHandler<GetUsersProductsByFriendlyUrlCompletedEventArgs> GetUsersProductsByFriendlyUrlCompleted;
        
        public event System.EventHandler<GetUsersProductsCompletedEventArgs> GetUsersProductsCompleted;
        
        public event System.EventHandler<System.ComponentModel.AsyncCompletedEventArgs> OpenCompleted;
        
        public event System.EventHandler<System.ComponentModel.AsyncCompletedEventArgs> CloseCompleted;
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.IAsyncResult WinPhoneClientProxy.ProductManagerService.IProductManager.BeginGetProductsInCategory(string categoryFriendlyUrl, int pageNumber, int productsPerPage, System.AsyncCallback callback, object asyncState) {
            return base.Channel.BeginGetProductsInCategory(categoryFriendlyUrl, pageNumber, productsPerPage, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WinPhoneClientProxy.ProductManagerService.InCategoryPLVM WinPhoneClientProxy.ProductManagerService.IProductManager.EndGetProductsInCategory(System.IAsyncResult result) {
            return base.Channel.EndGetProductsInCategory(result);
        }
        
        private System.IAsyncResult OnBeginGetProductsInCategory(object[] inValues, System.AsyncCallback callback, object asyncState) {
            string categoryFriendlyUrl = ((string)(inValues[0]));
            int pageNumber = ((int)(inValues[1]));
            int productsPerPage = ((int)(inValues[2]));
            return ((WinPhoneClientProxy.ProductManagerService.IProductManager)(this)).BeginGetProductsInCategory(categoryFriendlyUrl, pageNumber, productsPerPage, callback, asyncState);
        }
        
        private object[] OnEndGetProductsInCategory(System.IAsyncResult result) {
            WinPhoneClientProxy.ProductManagerService.InCategoryPLVM retVal = ((WinPhoneClientProxy.ProductManagerService.IProductManager)(this)).EndGetProductsInCategory(result);
            return new object[] {
                    retVal};
        }
        
        private void OnGetProductsInCategoryCompleted(object state) {
            if ((this.GetProductsInCategoryCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.GetProductsInCategoryCompleted(this, new GetProductsInCategoryCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void GetProductsInCategoryAsync(string categoryFriendlyUrl, int pageNumber, int productsPerPage) {
            this.GetProductsInCategoryAsync(categoryFriendlyUrl, pageNumber, productsPerPage, null);
        }
        
        public void GetProductsInCategoryAsync(string categoryFriendlyUrl, int pageNumber, int productsPerPage, object userState) {
            if ((this.onBeginGetProductsInCategoryDelegate == null)) {
                this.onBeginGetProductsInCategoryDelegate = new BeginOperationDelegate(this.OnBeginGetProductsInCategory);
            }
            if ((this.onEndGetProductsInCategoryDelegate == null)) {
                this.onEndGetProductsInCategoryDelegate = new EndOperationDelegate(this.OnEndGetProductsInCategory);
            }
            if ((this.onGetProductsInCategoryCompletedDelegate == null)) {
                this.onGetProductsInCategoryCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnGetProductsInCategoryCompleted);
            }
            base.InvokeAsync(this.onBeginGetProductsInCategoryDelegate, new object[] {
                        categoryFriendlyUrl,
                        pageNumber,
                        productsPerPage}, this.onEndGetProductsInCategoryDelegate, this.onGetProductsInCategoryCompletedDelegate, userState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.IAsyncResult WinPhoneClientProxy.ProductManagerService.IProductManager.BeginGetMainHighlighteds(int pageNumber, int productsPerPage, System.AsyncCallback callback, object asyncState) {
            return base.Channel.BeginGetMainHighlighteds(pageNumber, productsPerPage, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WinPhoneClientProxy.ProductManagerService.BookBlockPLVM WinPhoneClientProxy.ProductManagerService.IProductManager.EndGetMainHighlighteds(System.IAsyncResult result) {
            return base.Channel.EndGetMainHighlighteds(result);
        }
        
        private System.IAsyncResult OnBeginGetMainHighlighteds(object[] inValues, System.AsyncCallback callback, object asyncState) {
            int pageNumber = ((int)(inValues[0]));
            int productsPerPage = ((int)(inValues[1]));
            return ((WinPhoneClientProxy.ProductManagerService.IProductManager)(this)).BeginGetMainHighlighteds(pageNumber, productsPerPage, callback, asyncState);
        }
        
        private object[] OnEndGetMainHighlighteds(System.IAsyncResult result) {
            WinPhoneClientProxy.ProductManagerService.BookBlockPLVM retVal = ((WinPhoneClientProxy.ProductManagerService.IProductManager)(this)).EndGetMainHighlighteds(result);
            return new object[] {
                    retVal};
        }
        
        private void OnGetMainHighlightedsCompleted(object state) {
            if ((this.GetMainHighlightedsCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.GetMainHighlightedsCompleted(this, new GetMainHighlightedsCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void GetMainHighlightedsAsync(int pageNumber, int productsPerPage) {
            this.GetMainHighlightedsAsync(pageNumber, productsPerPage, null);
        }
        
        public void GetMainHighlightedsAsync(int pageNumber, int productsPerPage, object userState) {
            if ((this.onBeginGetMainHighlightedsDelegate == null)) {
                this.onBeginGetMainHighlightedsDelegate = new BeginOperationDelegate(this.OnBeginGetMainHighlighteds);
            }
            if ((this.onEndGetMainHighlightedsDelegate == null)) {
                this.onEndGetMainHighlightedsDelegate = new EndOperationDelegate(this.OnEndGetMainHighlighteds);
            }
            if ((this.onGetMainHighlightedsCompletedDelegate == null)) {
                this.onGetMainHighlightedsCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnGetMainHighlightedsCompleted);
            }
            base.InvokeAsync(this.onBeginGetMainHighlightedsDelegate, new object[] {
                        pageNumber,
                        productsPerPage}, this.onEndGetMainHighlightedsDelegate, this.onGetMainHighlightedsCompletedDelegate, userState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.IAsyncResult WinPhoneClientProxy.ProductManagerService.IProductManager.BeginGetNewests(int pageNumber, int productsPerPage, int numOfProducts, System.AsyncCallback callback, object asyncState) {
            return base.Channel.BeginGetNewests(pageNumber, productsPerPage, numOfProducts, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WinPhoneClientProxy.ProductManagerService.BookBlockPLVM WinPhoneClientProxy.ProductManagerService.IProductManager.EndGetNewests(System.IAsyncResult result) {
            return base.Channel.EndGetNewests(result);
        }
        
        private System.IAsyncResult OnBeginGetNewests(object[] inValues, System.AsyncCallback callback, object asyncState) {
            int pageNumber = ((int)(inValues[0]));
            int productsPerPage = ((int)(inValues[1]));
            int numOfProducts = ((int)(inValues[2]));
            return ((WinPhoneClientProxy.ProductManagerService.IProductManager)(this)).BeginGetNewests(pageNumber, productsPerPage, numOfProducts, callback, asyncState);
        }
        
        private object[] OnEndGetNewests(System.IAsyncResult result) {
            WinPhoneClientProxy.ProductManagerService.BookBlockPLVM retVal = ((WinPhoneClientProxy.ProductManagerService.IProductManager)(this)).EndGetNewests(result);
            return new object[] {
                    retVal};
        }
        
        private void OnGetNewestsCompleted(object state) {
            if ((this.GetNewestsCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.GetNewestsCompleted(this, new GetNewestsCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void GetNewestsAsync(int pageNumber, int productsPerPage, int numOfProducts) {
            this.GetNewestsAsync(pageNumber, productsPerPage, numOfProducts, null);
        }
        
        public void GetNewestsAsync(int pageNumber, int productsPerPage, int numOfProducts, object userState) {
            if ((this.onBeginGetNewestsDelegate == null)) {
                this.onBeginGetNewestsDelegate = new BeginOperationDelegate(this.OnBeginGetNewests);
            }
            if ((this.onEndGetNewestsDelegate == null)) {
                this.onEndGetNewestsDelegate = new EndOperationDelegate(this.OnEndGetNewests);
            }
            if ((this.onGetNewestsCompletedDelegate == null)) {
                this.onGetNewestsCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnGetNewestsCompleted);
            }
            base.InvokeAsync(this.onBeginGetNewestsDelegate, new object[] {
                        pageNumber,
                        productsPerPage,
                        numOfProducts}, this.onEndGetNewestsDelegate, this.onGetNewestsCompletedDelegate, userState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.IAsyncResult WinPhoneClientProxy.ProductManagerService.IProductManager.BeginGetUsersProductsByFriendlyUrl(string friendlyUrl, int pageNumber, int productsPerPage, bool forExchange, System.AsyncCallback callback, object asyncState) {
            return base.Channel.BeginGetUsersProductsByFriendlyUrl(friendlyUrl, pageNumber, productsPerPage, forExchange, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WinPhoneClientProxy.ProductManagerService.BookBlockPLVM WinPhoneClientProxy.ProductManagerService.IProductManager.EndGetUsersProductsByFriendlyUrl(out string userName, System.IAsyncResult result) {
            return base.Channel.EndGetUsersProductsByFriendlyUrl(out userName, result);
        }
        
        private System.IAsyncResult OnBeginGetUsersProductsByFriendlyUrl(object[] inValues, System.AsyncCallback callback, object asyncState) {
            string friendlyUrl = ((string)(inValues[0]));
            int pageNumber = ((int)(inValues[1]));
            int productsPerPage = ((int)(inValues[2]));
            bool forExchange = ((bool)(inValues[3]));
            return ((WinPhoneClientProxy.ProductManagerService.IProductManager)(this)).BeginGetUsersProductsByFriendlyUrl(friendlyUrl, pageNumber, productsPerPage, forExchange, callback, asyncState);
        }
        
        private object[] OnEndGetUsersProductsByFriendlyUrl(System.IAsyncResult result) {
            string userName = this.GetDefaultValueForInitialization<string>();
            WinPhoneClientProxy.ProductManagerService.BookBlockPLVM retVal = ((WinPhoneClientProxy.ProductManagerService.IProductManager)(this)).EndGetUsersProductsByFriendlyUrl(out userName, result);
            return new object[] {
                    userName,
                    retVal};
        }
        
        private void OnGetUsersProductsByFriendlyUrlCompleted(object state) {
            if ((this.GetUsersProductsByFriendlyUrlCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.GetUsersProductsByFriendlyUrlCompleted(this, new GetUsersProductsByFriendlyUrlCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void GetUsersProductsByFriendlyUrlAsync(string friendlyUrl, int pageNumber, int productsPerPage, bool forExchange) {
            this.GetUsersProductsByFriendlyUrlAsync(friendlyUrl, pageNumber, productsPerPage, forExchange, null);
        }
        
        public void GetUsersProductsByFriendlyUrlAsync(string friendlyUrl, int pageNumber, int productsPerPage, bool forExchange, object userState) {
            if ((this.onBeginGetUsersProductsByFriendlyUrlDelegate == null)) {
                this.onBeginGetUsersProductsByFriendlyUrlDelegate = new BeginOperationDelegate(this.OnBeginGetUsersProductsByFriendlyUrl);
            }
            if ((this.onEndGetUsersProductsByFriendlyUrlDelegate == null)) {
                this.onEndGetUsersProductsByFriendlyUrlDelegate = new EndOperationDelegate(this.OnEndGetUsersProductsByFriendlyUrl);
            }
            if ((this.onGetUsersProductsByFriendlyUrlCompletedDelegate == null)) {
                this.onGetUsersProductsByFriendlyUrlCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnGetUsersProductsByFriendlyUrlCompleted);
            }
            base.InvokeAsync(this.onBeginGetUsersProductsByFriendlyUrlDelegate, new object[] {
                        friendlyUrl,
                        pageNumber,
                        productsPerPage,
                        forExchange}, this.onEndGetUsersProductsByFriendlyUrlDelegate, this.onGetUsersProductsByFriendlyUrlCompletedDelegate, userState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.IAsyncResult WinPhoneClientProxy.ProductManagerService.IProductManager.BeginGetUsersProducts(int userID, int pageNumber, int productsPerPage, bool forExchange, System.AsyncCallback callback, object asyncState) {
            return base.Channel.BeginGetUsersProducts(userID, pageNumber, productsPerPage, forExchange, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WinPhoneClientProxy.ProductManagerService.BookBlockPLVM WinPhoneClientProxy.ProductManagerService.IProductManager.EndGetUsersProducts(System.IAsyncResult result) {
            return base.Channel.EndGetUsersProducts(result);
        }
        
        private System.IAsyncResult OnBeginGetUsersProducts(object[] inValues, System.AsyncCallback callback, object asyncState) {
            int userID = ((int)(inValues[0]));
            int pageNumber = ((int)(inValues[1]));
            int productsPerPage = ((int)(inValues[2]));
            bool forExchange = ((bool)(inValues[3]));
            return ((WinPhoneClientProxy.ProductManagerService.IProductManager)(this)).BeginGetUsersProducts(userID, pageNumber, productsPerPage, forExchange, callback, asyncState);
        }
        
        private object[] OnEndGetUsersProducts(System.IAsyncResult result) {
            WinPhoneClientProxy.ProductManagerService.BookBlockPLVM retVal = ((WinPhoneClientProxy.ProductManagerService.IProductManager)(this)).EndGetUsersProducts(result);
            return new object[] {
                    retVal};
        }
        
        private void OnGetUsersProductsCompleted(object state) {
            if ((this.GetUsersProductsCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.GetUsersProductsCompleted(this, new GetUsersProductsCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void GetUsersProductsAsync(int userID, int pageNumber, int productsPerPage, bool forExchange) {
            this.GetUsersProductsAsync(userID, pageNumber, productsPerPage, forExchange, null);
        }
        
        public void GetUsersProductsAsync(int userID, int pageNumber, int productsPerPage, bool forExchange, object userState) {
            if ((this.onBeginGetUsersProductsDelegate == null)) {
                this.onBeginGetUsersProductsDelegate = new BeginOperationDelegate(this.OnBeginGetUsersProducts);
            }
            if ((this.onEndGetUsersProductsDelegate == null)) {
                this.onEndGetUsersProductsDelegate = new EndOperationDelegate(this.OnEndGetUsersProducts);
            }
            if ((this.onGetUsersProductsCompletedDelegate == null)) {
                this.onGetUsersProductsCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnGetUsersProductsCompleted);
            }
            base.InvokeAsync(this.onBeginGetUsersProductsDelegate, new object[] {
                        userID,
                        pageNumber,
                        productsPerPage,
                        forExchange}, this.onEndGetUsersProductsDelegate, this.onGetUsersProductsCompletedDelegate, userState);
        }
        
        private System.IAsyncResult OnBeginOpen(object[] inValues, System.AsyncCallback callback, object asyncState) {
            return ((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(callback, asyncState);
        }
        
        private object[] OnEndOpen(System.IAsyncResult result) {
            ((System.ServiceModel.ICommunicationObject)(this)).EndOpen(result);
            return null;
        }
        
        private void OnOpenCompleted(object state) {
            if ((this.OpenCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.OpenCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void OpenAsync() {
            this.OpenAsync(null);
        }
        
        public void OpenAsync(object userState) {
            if ((this.onBeginOpenDelegate == null)) {
                this.onBeginOpenDelegate = new BeginOperationDelegate(this.OnBeginOpen);
            }
            if ((this.onEndOpenDelegate == null)) {
                this.onEndOpenDelegate = new EndOperationDelegate(this.OnEndOpen);
            }
            if ((this.onOpenCompletedDelegate == null)) {
                this.onOpenCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnOpenCompleted);
            }
            base.InvokeAsync(this.onBeginOpenDelegate, null, this.onEndOpenDelegate, this.onOpenCompletedDelegate, userState);
        }
        
        private System.IAsyncResult OnBeginClose(object[] inValues, System.AsyncCallback callback, object asyncState) {
            return ((System.ServiceModel.ICommunicationObject)(this)).BeginClose(callback, asyncState);
        }
        
        private object[] OnEndClose(System.IAsyncResult result) {
            ((System.ServiceModel.ICommunicationObject)(this)).EndClose(result);
            return null;
        }
        
        private void OnCloseCompleted(object state) {
            if ((this.CloseCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.CloseCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void CloseAsync() {
            this.CloseAsync(null);
        }
        
        public void CloseAsync(object userState) {
            if ((this.onBeginCloseDelegate == null)) {
                this.onBeginCloseDelegate = new BeginOperationDelegate(this.OnBeginClose);
            }
            if ((this.onEndCloseDelegate == null)) {
                this.onEndCloseDelegate = new EndOperationDelegate(this.OnEndClose);
            }
            if ((this.onCloseCompletedDelegate == null)) {
                this.onCloseCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnCloseCompleted);
            }
            base.InvokeAsync(this.onBeginCloseDelegate, null, this.onEndCloseDelegate, this.onCloseCompletedDelegate, userState);
        }
        
        protected override WinPhoneClientProxy.ProductManagerService.IProductManager CreateChannel() {
            return new ProductManagerClientChannel(this);
        }
        
        private class ProductManagerClientChannel : ChannelBase<WinPhoneClientProxy.ProductManagerService.IProductManager>, WinPhoneClientProxy.ProductManagerService.IProductManager {
            
            public ProductManagerClientChannel(System.ServiceModel.ClientBase<WinPhoneClientProxy.ProductManagerService.IProductManager> client) : 
                    base(client) {
            }
            
            public System.IAsyncResult BeginGetProductsInCategory(string categoryFriendlyUrl, int pageNumber, int productsPerPage, System.AsyncCallback callback, object asyncState) {
                object[] _args = new object[3];
                _args[0] = categoryFriendlyUrl;
                _args[1] = pageNumber;
                _args[2] = productsPerPage;
                System.IAsyncResult _result = base.BeginInvoke("GetProductsInCategory", _args, callback, asyncState);
                return _result;
            }
            
            public WinPhoneClientProxy.ProductManagerService.InCategoryPLVM EndGetProductsInCategory(System.IAsyncResult result) {
                object[] _args = new object[0];
                WinPhoneClientProxy.ProductManagerService.InCategoryPLVM _result = ((WinPhoneClientProxy.ProductManagerService.InCategoryPLVM)(base.EndInvoke("GetProductsInCategory", _args, result)));
                return _result;
            }
            
            public System.IAsyncResult BeginGetMainHighlighteds(int pageNumber, int productsPerPage, System.AsyncCallback callback, object asyncState) {
                object[] _args = new object[2];
                _args[0] = pageNumber;
                _args[1] = productsPerPage;
                System.IAsyncResult _result = base.BeginInvoke("GetMainHighlighteds", _args, callback, asyncState);
                return _result;
            }
            
            public WinPhoneClientProxy.ProductManagerService.BookBlockPLVM EndGetMainHighlighteds(System.IAsyncResult result) {
                object[] _args = new object[0];
                WinPhoneClientProxy.ProductManagerService.BookBlockPLVM _result = ((WinPhoneClientProxy.ProductManagerService.BookBlockPLVM)(base.EndInvoke("GetMainHighlighteds", _args, result)));
                return _result;
            }
            
            public System.IAsyncResult BeginGetNewests(int pageNumber, int productsPerPage, int numOfProducts, System.AsyncCallback callback, object asyncState) {
                object[] _args = new object[3];
                _args[0] = pageNumber;
                _args[1] = productsPerPage;
                _args[2] = numOfProducts;
                System.IAsyncResult _result = base.BeginInvoke("GetNewests", _args, callback, asyncState);
                return _result;
            }
            
            public WinPhoneClientProxy.ProductManagerService.BookBlockPLVM EndGetNewests(System.IAsyncResult result) {
                object[] _args = new object[0];
                WinPhoneClientProxy.ProductManagerService.BookBlockPLVM _result = ((WinPhoneClientProxy.ProductManagerService.BookBlockPLVM)(base.EndInvoke("GetNewests", _args, result)));
                return _result;
            }
            
            public System.IAsyncResult BeginGetUsersProductsByFriendlyUrl(string friendlyUrl, int pageNumber, int productsPerPage, bool forExchange, System.AsyncCallback callback, object asyncState) {
                object[] _args = new object[4];
                _args[0] = friendlyUrl;
                _args[1] = pageNumber;
                _args[2] = productsPerPage;
                _args[3] = forExchange;
                System.IAsyncResult _result = base.BeginInvoke("GetUsersProductsByFriendlyUrl", _args, callback, asyncState);
                return _result;
            }
            
            public WinPhoneClientProxy.ProductManagerService.BookBlockPLVM EndGetUsersProductsByFriendlyUrl(out string userName, System.IAsyncResult result) {
                object[] _args = new object[1];
                WinPhoneClientProxy.ProductManagerService.BookBlockPLVM _result = ((WinPhoneClientProxy.ProductManagerService.BookBlockPLVM)(base.EndInvoke("GetUsersProductsByFriendlyUrl", _args, result)));
                userName = ((string)(_args[0]));
                return _result;
            }
            
            public System.IAsyncResult BeginGetUsersProducts(int userID, int pageNumber, int productsPerPage, bool forExchange, System.AsyncCallback callback, object asyncState) {
                object[] _args = new object[4];
                _args[0] = userID;
                _args[1] = pageNumber;
                _args[2] = productsPerPage;
                _args[3] = forExchange;
                System.IAsyncResult _result = base.BeginInvoke("GetUsersProducts", _args, callback, asyncState);
                return _result;
            }
            
            public WinPhoneClientProxy.ProductManagerService.BookBlockPLVM EndGetUsersProducts(System.IAsyncResult result) {
                object[] _args = new object[0];
                WinPhoneClientProxy.ProductManagerService.BookBlockPLVM _result = ((WinPhoneClientProxy.ProductManagerService.BookBlockPLVM)(base.EndInvoke("GetUsersProducts", _args, result)));
                return _result;
            }
        }
    }
}
